# Configuraci贸n para el entorno de desarrollo
development:
  adapter: postgres
  host: localhost
  database: postgres
  user: postgres
  password: aterronm

# Configuraci贸n para el entorno de pruebas
test:
  adapter: postgres
  host: localhost
  database: test_database_name
  user: test_username
  password: test_password

# Configuraci贸n para el entorno de producci贸n
production:
  adapter: postgres
  host: localhost
  database: test_database_name
  user: test_username
  password: test_password